version: '3.7'

services:
  orinz_database:
    container_name: "orinz-dev"
    image: "orinz-database"
    restart: always
    build:
      context: application/drivers/database/sql/
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orinz-dev
      MYSQL_USER: spurgeon
      MYSQL_PASSWORD: spurgeon
    ports:
      - "3306:3306"

    volumes:
      - ./init:/docker-entrypoint-initdb.d