version: "3.7"

services:
  orinz_database:
    image: mysql
    container_name: orinz_db
    build:
      context: ./application/drivers/database/sql
      dockerfile: Dockerfile
    ports:
      - "3306:3036"
    restart: on-failure
    environment:
      APP_DB_NAME: orinz_db_dev
      APP_DB_PASS: docker
      APP_DB_USER: docker
      POSTGRES_PASSWORD: "gotham"
      POSTGRES_USER: "joker"
    volumes:
     - .:/docker-entrypoint-initdb.d/